name: Test
on:
  - push
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Ubuntu ${{ matrix.ubuntu }}, Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ubuntu: [20.04, 22.04]
        ruby: ['3.0', '3.1', '3.2']
    runs-on: ubuntu-${{ matrix.ubuntu }}
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Setup ruby
      continue-on-error: true
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        rubygems: 3.4.10
        bundler-cache: true
    - name: Run tests
      continue-on-error: true
      run: |
        gem list
        bundle show psych
        bundle show mini_racer
        ruby -ryaml -e 'puts YAML.safe_load("---\nhello: world\n").inspect'
        ruby -ryaml -e "puts Psych::Parser.new.respond_to?(:parse)"
        ruby -ryaml -e 'YAML.safe_load("--- !ruby/object:Libv8::Node::Location::Vendor {}")'
        bundle exec ruby -ryaml -e 'puts YAML.safe_load("---\nhello: world\n").inspect'
        bundle exec ruby -ryaml -e "puts Psych::Parser.new.respond_to?(:parse)"
        bundle exec ruby -ryaml -e 'YAML.safe_load("--- !ruby/object:Libv8::Node::Location::Vendor {}")'
